#!/usr/bin/env bash

icons22=(
    "fileNew"
    "fileSave"
    "editCopy"
    "editCut"
    "editDelete"
    "editModeDraw"
    "editModeOff"
    "editModeOn"
    "editPaste"
    "editRedo"
    "editSelectClip"
    "editSelectCurve"
    "editSelectRange"
    "editSelectRect"
    "editUndo"
    "clipNew"
    "clipEdit"
    "clipRecord"
    "clipProperties"
    "trackAudio"
    "trackMidi"
    "viewConnections"
    "viewDrumMode"
    "viewEvents"
    "viewFiles"
    "viewFileSystem"
    "viewMesseges"
    "viewMixer"
    "viewPreview"
    "viewZoomIn"
    "viewZoomOut"
    "viewZoomReset"
    "viewZoomTool"
    "helpShortcuts"
    "formSave"
    "formRemove"
    "formReject"
    "formRefresh"
    "formOpen"
    "formEdit"
    "formMoveUp"
    "formMoveDown"
    "formDisconnectAll"
    "formDisconnect"
    "formCreate"
    "formConnect"
    "formAdd"
    "formAccept"
    "pluginEdit"
    "pluginProperties"
    "qtractorConnections"
    "qtractorMidiEdtor"
    "qtractorMixer"
    "qtractorPlugin"
    "qtractorTracks"
    )

icons16=(

    "itemAudioClientIn"
    "itemAudioClientOut"
    "itemAudioFile"
    "itemAudioPortIn"
    "itemAudioPortOut"
    "itemAudioPortPhysIn"
    "itemAudioPortPhysOut"
    "itemBeat"
    "itemCdUp"
    "itemChannel"
    "itemClear"
    "itemControllers"
    "itemFile"
    "itemGroupOpen"
    "itemGroup"
    "itemHome"
    "itemInstrument"
    "itemMidiClientIn"
    "itemMidiClientOut"
    "itemMidiFile"
    "itemMidiPortIn"
    "itemMidiPortOut"
    "itemNone"
    "itemNotes"
    "itemNrpns"
    "itemPatches"
    "itemProperty"
    "itemReset"
    "itemRpns"
    "itemSessionFile"
    )

for icon in "${icons22[@]}"; do
  cp clear-22x22.png "$icon".png
done

for icon in "${icons16[@]}"; do
  cp clear-16x16.png "$icon".png
done


